# These are supported funding model platforms

github: [potatoqualitee, wsmelton, Stuart-Moore, sanderstad, claudioessilva]
patreon: potatoqualitee
open_collective: dbatools
custom: paypal.me/potatoqualitee
